# Generated by Django 6.0.2 on 2026-02-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_profilephoto_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('improvement_from_last', models.FloatField()),
                ('improvement_from_first', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='profiles.profile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profileversion')),
            ],
        ),
    ]
