# Generated by Django 6.0.2 on 2026-02-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
