# Generated by Django 6.0.2 on 2026-02-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('liked', models.TextField()),
                ('disliked', models.TextField()),
                ('suggestions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profileversion')),
                ('review_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requests.reviewrequest')),
            ],
        ),
    ]
