# Generated by Django 6.0.2 on 2026-02-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='quick_impression',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
