# Generated by Django 6.0.2 on 2026-02-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileversion',
            name='improvement_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profileversion',
            name='negative_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileversion',
            name='positive_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_custom', models.BooleanField(default=False)),
                ('profile_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='profiles.profileversion')),
            ],
        ),
    ]
