# Generated by Django 6.0.2 on 2026-02-13 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age_alter_user_gender_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='public_username',
            field=models.CharField(default='anonymous', max_length=50, unique=True),
        ),
    ]
